name: CI

on:
  pull_request:
    branches: ["**"]
    types: [labeled, unlabeled, opened, synchronize, reopened]

# Cancel previous workflows if they are the same workflow on same ref (branch/tags)
# with the same event (push/pull_request) even they are in progress.
# This setting will help reduce the number of duplicated workflows.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - run: |
          if bash .script/is_folder_updated.sh backend; then
            cd backend;
            yarn --frozen-lockfile;
            yarn format;
            yarn lint;
            CI=true yarn test --testPathIgnorePatterns="e2e";
          else
            echo "No backend changes, skip backend CI";
          fi

      - run: |
          if bash .script/is_folder_updated.sh frontend; then
            cd frontend;
            yarn --frozen-lockfile;
            yarn format;
            yarn lint;
            CI=true yarn test --testPathIgnorePatterns="e2e";
          else
            echo "No frontend changes, skip frontend CI";
          fi

      - run: bash .script/check_test_file_path_convention.sh
